require 'json'
require 'date'
require 'time'
require 'uri'
require 'httparty'

require_relative 'nikeplusgem/client'
require_relative 'nikeplusgem/version'
require_relative 'nikeplusgem/list_activities'
require_relative 'nikeplusgem/aggregate_sport'
require_relative 'nikeplusgem/experience_type'
require_relative 'nikeplusgem/activity_data'
require_relative 'nikeplusgem/extensions'
require_relative 'nikeplusgem/helpers'